name: testapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  email_validator: '^2.1.16'
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  flutter_keyboard_visibility: ^6.0.0
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'  
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
  assets:
     - assets/
     
